### ISSUE TITLE
HuddleLamp tracking software?

### ISSUE THREAD

**Issue by floe** [raedle/meteor-huddle#1]
The HuddleLamp tracking software seems to be unavailable, here on Github as well as on the huddlelamp.org website. Are there any plans for an upcoming release?

Thanks, Florian

**Comment by raedle** [comment]
Hi Florian,

Thank you for the interest in HuddleLamp tracking software. We haven't had time yet to release the software properly. Documentation is still missing. But send me a pm with your Bitbucket.org account name and we'll invite you to the Git repository.

Best,
Roman

**Comment by floe** [comment]
Hello Roman,

thanks - Bitbucket username is "floemuc".

Best regards, Florian

On Tue, 24 Feb 2015, Roman Rädle wrote:

> Hi Florian,
> 
> Thank you for the interest in HuddleLamp tracking software. We haven't had time yet to release the software properly. Documentation is
> still missing. But send me a pm with your Bitbucket.org account name and we'll invite you to the Git repository.
> 
> Best,
> Roman
> 
> —
> Reply to this email directly or view it on GitHub.[AAFihLxhsciOs7D94Vjq6HfQk4OetihDks5nvVLHgaJpZM4Dg6UE.gif]

## 

"_Nothing_ brightens up my morning. Coffee simply provides a shade of
grey just above the pitch-black of the infinite depths of the _abyss_."

**Comment by raedle** [comment]
Ok. You have access now. Have fun!
